### ISSUE TITLE
Доработки версии 0.2.0

### ISSUE THREAD

**Issue by ensrationis** [airalab/DAO-IPCI#10]
- [x] Пересоздать ДАО в официальной сети
- [x] Адрес оператора в создании контракта аудитора
- [ ] Описание механизма комиссий рынка в [AIPs DAO Airalab](https://github.com/airalab/DAO-Airalab/tree/master/AIPs)

**Comment by EvgenRad81** [comment]
Про комиссию рынка уже не помню о чем речь. Если что переоткроем.
