### ISSUE TITLE
Add DApp on dapps.ethercasts.com

### ISSUE THREAD

**Issue by ensrationis** [airalab/DAO-IPCI#11]
http://dapps.ethercasts.com/

**Comment by EvgenRad81** [comment]
Форму заполнил. Ждем результат.

**Comment by EvgenRad81** [comment]
done
![screenshot_2](https://cloud.githubusercontent.com/assets/8296742/24038500/1cb057fe-0b1b-11e7-8b62-deb395f6615c.jpg)
