### ISSUE TITLE
Обязательства на платформе

### ISSUE THREAD

**Issue by ensrationis** [airalab/DAO-IPCI#9]
Сейчас мы имеем контракт страхования эмиссии, в котором оператор задаёт процент единиц от выпуска единиц. Требуется разработать сейчас аналогичный контракт, который будет требовать наличия на своём счету других токенов (потенциально внутреннего расчетного токена рынка DAO IPCI) и оператор задаёт процент, в пределах которого эмитент может вывести единицы на платформу. 
Для примера: оператор задаёт 10% и указывает адрес контракта принимаемого токена с названием "Carbon trading unit". Эмитент переводит на счет контракта 1000 Carbon trading unit и тем самым может эмиссировать до 10 000 своих токенов.

**Comment by vol4tim** [comment]
https://github.com/airalab/DAO-IPCI/commit/4b12d463b3f33e4d220f7141242439a47529517c
